# Cloudflare Pages configuration for MyAIware.com
name = "myaiware-web"
compatibility_date = "2024-10-03"
pages_build_output_dir = "dist"

# Environment variables (set these in Cloudflare Pages dashboard)
# NUXT_PUBLIC_CLOUDINARY_CLOUD_NAME
# NUXT_PUBLIC_API_BASE
# NUXT_PUBLIC_TURNSTILE_SITE_KEY
# NUXT_PUBLIC_SITE_URL
